---
filebeat_repo_manage: yes
filebeat_package_names: filebeat
filebeat_package_state: present
filebeat_conf_manage: yes
filebeat_conf_path: /etc/filebeat/filebeat.yml
filebeat_modules_path: /etc/filebeat/modules.d/*.yml
filebeat_service_name: filebeat
filebeat_service_status: started
filebeat_service_enabled: yes
filebeat_package_hold: no

filebeat_conf_elasticsearch_enabled: true
filebeat_conf_elasticsearch_loadbalance: true
filebeat_conf_elasticsearch_port: 9200
filebeat_conf_elasticsearch_hosts: ['localhost']

filebeat_conf_logstash_enabled: false
filebeat_conf_logstash_loadbalance: true
filebeat_conf_logstash_port: 5044
filebeat_conf_logstash_hosts: ['localhost']

filebeat_conf_dashboards_enabled: false
filebeat_conf_dashboards_kibana: true
filebeat_conf_template_enabled: true
filebeat_conf_kibana_host: 'localhost:80'

filebeat_conf_modules: []
filebeat_conf_inputs: []

filebeat_conf_extra: {}

filebeat_conf_output_elasticsearch:
  enabled: "{{ filebeat_conf_elasticsearch_enabled }}"
  hosts: "{{ filebeat_conf_elasticsearch_hosts | map('map_format', '%s:' + (filebeat_conf_elasticsearch_port | string)) | list }}"
  loadbalance: "{{ filebeat_conf_elasticsearch_loadbalance }}"

filebeat_conf_output_logstash:
  enabled: "{{ filebeat_conf_logstash_enabled }}"
  hosts: "{{ filebeat_conf_logstash_hosts | map('map_format', '%s:' + (filebeat_conf_logstash_port | string)) | list }}"
  loadbalance: "{{ filebeat_conf_logstash_loadbalance }}"

filebeat_conf_output:
  elasticsearch: "{{ filebeat_conf_output_elasticsearch }}"
  logstash: "{{ filebeat_conf_output_logstash }}"

filebeat_conf_setup:
  dashboards:
    enabled: "{{ filebeat_conf_dashboards_enabled }}"
    beat: filebeat
    always_kibana: "{{ filebeat_conf_dashboards_kibana }}"
  template:
    enabled: "{{ filebeat_conf_template_enabled }}"
  kibana:
    host: "{{ filebeat_conf_kibana_host }}"

filebeat_conf_logging:
  level: warning
  to_syslog: false
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644

filebeat_conf_base:
  filebeat:
    modules: "{{ filebeat_conf_modules }}"
    config:
      modules:
        path: "{{ filebeat_modules_path }}"
    inputs: "{{ filebeat_conf_inputs }}"
  output: "{{ filebeat_conf_output }}"
  setup: "{{ filebeat_conf_setup }}"
  logging: "{{ filebeat_conf_logging }}"

filebeat_conf: "{{ filebeat_conf_base | combine(filebeat_conf_extra) }}"
